### ISSUE TITLE
Example of how to use rakyll/statik with fiber

### ISSUE THREAD

**Issue by jeffotoni** [gofiber/embed#14]
```go
// Example of how to use rakyll/statik to embed the binary in your executable
// go get github.com/rakyll/statik
// statik -src = <Your html>/

package main

import (
	"log"
	"github.com/gofiber/embed"
	"github.com/gofiber/fiber"
	
	"<Your go module>/statik"
	"github.com/rakyll/statik/fs"
)

func main() {

	statikFS, err := fs.New()
	if err != nil {
		log.Fatal(err)
	}

	app := fiber.New()

	app.Use("/", embed.New(embed.Config{
		Root: statikFS,
	}))

	app.Listen(8080)
}

```

**Comment by Fenny** [comment]
Assuming you have a question on how the `embed` middleware works with the `rakyll/statik` package, you can follow the [how-to docs here](https://github.com/rakyll/statik#usage).

**Comment by jeffotoni** [comment]
I actually implemented using fiber our colleague rakyll / statik.
In other words, I can embed all html, css, js, img within the binary.
And above is the example that will work

**Comment by Fenny** [comment]
Awesome work, we will add this example to the readme!

**Comment by Fenny** [comment]
https://github.com/gofiber/embed/pull/15
